import React, { useState } from "react";
import "./gallery.css";

const Gallery = () => {
  return (
    <div className="gallery p-5" id="gallery">
      <div className="pslv">
        <h1 className="gallery-title">Gallery</h1>
        <div className="image-container">
          <img
            className="gallery-image"
            src="https://www.isro.gov.in/media_isro/image/media/Missions/PSLV/more/PSLV52/gallery/resized/1_medium.jpg.webp"
            alt=""
          />
          <img
            className="gallery-image"
            src="https://www.isro.gov.in/media_isro/image/media/Missions/PSLV/more/PSLV52/gallery/resized/3_medium.jpg.webp"
            alt=""
          />
          <img
            className="image 1"
            src="https://www.isro.gov.in/media_isro/image/media/Missions/PSLV/more/PSLV52/gallery/resized/1_medium.jpg.webp"
          ></img>
          <img
            className="image 2"
            src="https://www.isro.gov.in/media_isro/image/media/Missions/PSLV/more/PSLV52/gallery/resized/3_medium.jpg.webp"
          ></img>
          <img
            src="https://www.isro.gov.in/media_isro/image/media/Missions/PSLV/more/PSLV52/gallery/resized/4a_medium.jpg.webp"
            alt=""
            className="image 3"
          />
          <img
            src="https://www.isro.gov.in/media_isro/image/media/Missions/PSLV/more/PSLV52/gallery/resized/5_medium.jpg.webp"
            alt=""
            className="image 4"
          />
          <img
            src="https://www.isro.gov.in/media_isro/image/media/Missions/PSLV/more/PSLV52/gallery/resized/5a_medium.jpg.webp"
            alt=""
            className="image 5"
          />
          <img
            src="https://www.isro.gov.in/media_isro/image/media/Missions/PSLV/more/PSLV52/gallery/resized/7_medium.jpg.webp"
            alt=""
            className="image"
          />
          <img
            src="https://www.isro.gov.in/media_isro/image/media/Missions/PSLV/more/PSLV52/gallery/resized/10_medium.jpg.webp"
            alt=""
            className="image"
          />
          <img
            src="https://www.isro.gov.in/media_isro/image/media/Missions/PSLV/more/PSLV52/gallery/resized/11_medium.jpg.webp"
            alt=""
            className="image"
          />
          <img
            src="https://www.isro.gov.in/media_isro/image/media/Missions/PSLV/more/PSLV52/gallery/resized/12_medium.jpg.webp"
            alt=""
            className="image"
          />

          <img
            src="https://www.isro.gov.in/media_isro/image/media/Missions/PSLV/more/PSLV52/gallery/resized/17_medium.jpg.webp"
            alt=""
            className="image"
          />
          <img
            src="https://www.isro.gov.in/media_isro/image/media/Missions/PSLV/more/PSLV52/gallery/resized/c529267_medium.jpg.webp"
            alt=""
            className="image"
          />
          <img
            src="https://www.isro.gov.in/media_isro/image/media/Missions/PSLV/more/PSLV52/gallery/resized/19_medium.jpg.webp"
            alt=""
            className="image"
          />
          <img
            src="https://www.isro.gov.in/media_isro/image/media/Missions/PSLV/more/PSLV52/gallery/resized/20_medium.jpg.webp"
            alt=""
            className="image"
          />
          <img
            src="https://www.isro.gov.in/media_isro/image/media/Missions/PSLV/more/PSLV52/gallery/resized/21_medium.jpg.webp"
            alt=""
            className="image"
          />
          <img
            src="https://www.isro.gov.in/media_isro/image/media/Missions/PSLV/more/PSLV52/gallery/resized/23_medium.jpg.webp"
            alt=""
            className="image"
          />

          <img
            src="https://upload.wikimedia.org/wikipedia/commons/6/60/LVM3_M4%2C_Chandrayaan-3_-_Fully_assembled_launch_vehicle_being_transported_from_Second_Vehicle_Assembly_Building_%28SVAB%29_to_Second_Launch_Pad_%28SLP%29_04.webp"
            alt=""
            className="image"
          />

          <img
            src="https://i0.wp.com/www.orissapost.com/wp-content/uploads/2023/07/rocket.jpg?fit=497%2C273&ssl=1"
            alt=""
            className="image"
          />

          <img
            src="https://images.moneycontrol.com/static-mcnews/2023/07/Chandrayaan-3.0.jpg?impolicy=website&width=770&height=431"
            alt=""
            className="image"
          />

          <img
            src="https://www.isro.gov.in/media_isro/image/media/Missions/PSLV/more/PSLV52/gallery/resized/24_medium.jpg.webp"
            alt=""
            className="image"
          />
          <img
            src="https://www.isro.gov.in/media_isro/image/media/Missions/PSLV/more/PSLV52/gallery/resized/26_medium.jpg.webp"
            alt=""
            className="image"
          />
          <img
            src="https://www.isro.gov.in/media_isro/image/media/Missions/PSLV/more/PSLV52/gallery/resized/27_medium.jpg.webp"
            alt=""
            className="image"
          />
          <img
            src="https://th-i.thgim.com/public/latest-news/5sevra/article67081572.ece/alternates/FREE_1200/Chandryaan3.JPG"
            alt=""
            className="image"
          />

          <img
            src="https://pbs.twimg.com/media/F0QillXaQAAcbF5?format=jpg&name=4096x4096"
            alt=""
            className="image"
          />
          <img
            src="https://www.isro.gov.in/media_isro/image/media/Missions/PSLV/more/PSLV52/gallery/resized/29_medium.jpg.webp"
            alt=""
            className="image"
          />
          <img
            src="https://www.isro.gov.in/media_isro/image/media/Missions/PSLV/more/PSLV52/gallery/resized/bjs0005_medium.jpg.webp"
            alt=""
            className="image"
          />
          <img
            src="https://www.isro.gov.in/media_isro/image/media/Missions/PSLV/more/PSLV52/gallery/resized/c520776_medium.jpg.webp"
            alt=""
            className="image"
          />
          <img
            src="https://www.isro.gov.in/media_isro/image/media/Missions/PSLV/more/PSLV52/gallery/resized/c520807_medium.jpg.webp"
            alt=""
            className="image"
          />
          <img
            src="https://www.isro.gov.in/media_isro/image/media/Missions/PSLV/more/PSLV52/gallery/resized/c520828_medium.jpg.webp"
            alt=""
            className="image"
          />
          <img
            src="https://www.isro.gov.in/media_isro/image/media/Missions/PSLV/more/PSLV52/gallery/resized/c529253_medium.jpg.webp"
            alt=""
            className="image"
          />
          <img
            src="https://www.isro.gov.in/media_isro/image/media/Missions/PSLV/more/PSLV52/gallery/resized/c529267_medium.jpg.webp"
            alt=""
            className="image"
          />
          <img
            src="https://www.isro.gov.in/media_isro/image/media/Missions/PSLV/more/PSLV52/gallery/resized/dks3012_medium.jpg.webp"
            alt=""
            className="image"
          />
          <img
            src="https://www.isro.gov.in/media_isro/image/media/Missions/PSLV/more/PSLV52/gallery/resized/dks7598_medium.jpg.webp"
            alt=""
            className="image"
          />
          <img
            src="https://www.isro.gov.in/media_isro/image/media/Missions/PSLV/more/PSLV52/gallery/resized/eos-04_medium.jpg.webp"
            alt=""
            className="image"
          />
          <img
            src="https://www.isro.gov.in/media_isro/image/media/Missions/PSLV/more/PSLV52/gallery/resized/imgl4965_medium.jpg.webp"
            alt=""
            className="image"
          />
          <img
            src="https://www.isro.gov.in/media_isro/image/media/Missions/PSLV/more/PSLV52/gallery/resized/imgl4999_medium.jpg.webp"
            alt=""
            className="image"
          />
          <img
            src="https://www.isro.gov.in/media_isro/image/media/Missions/PSLV/more/PSLV52/gallery/resized/imgl5017_medium.jpg.webp"
            alt=""
            className="image"
          />
          <img
            src="https://www.isro.gov.in/media_isro/image/media/Missions/PSLV/more/PSLV52/gallery/resized/imgl5028_medium.jpg.webp"
            alt=""
            className="image"
          />
          <img
            src="https://www.isro.gov.in/media_isro/image/media/Missions/PSLV/more/PSLV52/gallery/resized/imgl5034_medium.jpg.webp"
            alt=""
            className="image"
          />
          <img
            src="https://www.isro.gov.in/media_isro/image/media/Missions/PSLV/more/PSLV52/gallery/resized/ins-2td_medium.jpg.webp"
            alt=""
            className="image"
          />
          <img
            src="https://www.isro.gov.in/media_isro/image/media/Missions/PSLV/more/PSLV52/gallery/resized/inspiresat_medium.jpg.webp"
            alt=""
            className="image"
          />
          <img
            src="https://www.isro.gov.in/media_isro/image/media/Missions/PSLV/more/PSLV52/gallery/resized/psk6955_medium.jpg.webp"
            alt=""
            className="image"
          />
          <img
            src="https://www.isro.gov.in/media_isro/image/media/Missions/PSLV/more/PSLV52/gallery/resized/psk6969_medium.jpg.webp"
            alt=""
            className="image"
          />
          <img
            src="https://www.isro.gov.in/media_isro/image/media/Missions/PSLV/more/PSLV52/gallery/resized/yrn7963_medium.jpg.webp"
            alt=""
            className="image"
          />
          <img
            src="https://www.isro.gov.in/media_isro/image/media/Missions/PSLV/more/PSLV52/gallery/resized/yrnl3539_medium.jpg.webp"
            alt=""
            className="image"
          />
          <img
            src="https://www.isro.gov.in/media_isro/image/media/Missions/PSLV/more/PSLV52/gallery/resized/yrnl3542_medium.jpg.webp"
            alt=""
            className="image"
          />
        </div>
      </div>
    </div>
  );
};

export default Gallery;
